### ISSUE TITLE
怎么实现布局的设计？

### ISSUE THREAD

**Issue by eddy99** [dream2023/vue-ele-form-generator#10]
在设计器里怎么扩展布局控件？

**Comment by dream2023** [comment]
意思是增加组件吗？

**Comment by eddy99** [comment]
发送自 Windows 10 版邮件应用

发件人: 张超杰
发送时间: 2020年1月10日 21:01
收件人: dream2023/vue-ele-form-generator
抄送: eddy99; Author
主题: Re: [dream2023/vue-ele-form-generator] 怎么实现布局的设计？ (#10)

意思是增加组件吗？
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
你好！
想增加一个布局组件(例如：一行两列布局)，其他普通控件可以拖拽到布局组件中。还没有仔细看源码，先请教一下这样的需求在现有的框架中可以通过自己扩展组件的方式实现吗？😀

**Comment by dream2023** [comment]
![image](https://user-images.githubusercontent.com/19297757/72159371-2d68c100-33f7-11ea-8cdf-4a436e3818f9.png)

**Comment by dream2023** [comment]
> 在设计器里怎么扩展布局控件？

拖动layout到12就行了，想一列多少就拖到多少就行了
