### ISSUE TITLE
表单元素宽度是否可修改

### ISSUE THREAD

**Issue by xzusoft** [dream2023/vue-ele-form-generator#14]
现在默认是6，可否自定义，现有layout，只在小屏下有效

**Comment by dream2023** [comment]
你值得是inline吗？

**Comment by xzusoft** [comment]
是的

**Comment by dream2023** [comment]
你想改成什么样？

**Comment by dream2023** [comment]
不太明白

**Comment by xzusoft** [comment]
最好是可以自定义，比如一个状态下拉框，我只想给他4个栅格，方便加一下QQ  或者微信吗，交流起来更加方便

**Comment by xzusoft** [comment]
现在最多放四个是挺科学，但在大屏幕下就会出现很长的文本框，不美观

**Comment by xzusoft** [comment]
我的QQ1614040526，微信zj880910

**Comment by dream2023** [comment]
现在就可以指定，https://www.yuque.com/chaojie-vjiel/vbwzgu/iw5dzf#uuQkg
