### ISSUE TITLE
表单项提示小bug

### ISSUE THREAD

**Issue by isboyjc** [dream2023/vue-ele-form-generator#16]
发现一个小bug，输入英文数字不换行，css需要改下，哈哈
![image](https://user-images.githubusercontent.com/42193415/73635420-75010680-469e-11ea-953a-d4b7e96fa436.png)

**Comment by dream2023** [comment]
我又确认了一下，只有连续字母才会出现这个情况，中文或者字母有空格都没有，但是如果设置 `word-break: break-all`，正常单词的换行就出问题，所以保持原状
