### ISSUE TITLE
支持json schema反向生成表单的功能，就很完美了

### ISSUE THREAD

**Issue by majintao** [dream2023/vue-ele-form-generator#22]
类似这样：https://json-editor.github.io/json-editor/

**Comment by dream2023** [comment]
![image](https://user-images.githubusercontent.com/19297757/74907860-3cc42c80-53ef-11ea-9f5f-45de420becf7.png)
本身支持

**Comment by majintao** [comment]
这数据格式是你自定义的，我指的是 标准的Json schema数据定义

**Comment by dream2023** [comment]
> 这数据格式是你自定义的，我指的是 标准的Json schema数据定义
![image](https://user-images.githubusercontent.com/19297757/74910562-c119ae00-53f5-11ea-895f-c7cf4bf8bbbe.png)

我不知道你说的标准是什么

```js
{
  "formDesc": {
    "name": {
      "label": "姓名",
      "type": "input",
      "layout": 12
    },
    "age": {
      "label": "年龄",
      "type": "input",
      "layout": 12
    },
    "desc": {
      "label": "描述",
      "type": "quill-editor",
      "attrs": {
        "action": "https://jsonplaceholder.typicode.com/posts"
      }
    }
  }
}
```

**Comment by majintao** [comment]
https://baike.baidu.com/item/jsonschema/15275465?fr=aladdin  （百度百科，标准的json shcema）

合法格式：
{ 
    "type": "object",
    "properties": {
        "city": { "type": "string" },
        "number": { "type": "number" },
        "user": { 
            "type": "object",
            "properties": {
                "name" : {"type": "string"},
                "age" : {"type": "number"}
            }                       
        }
    }
}
