### ISSUE TITLE
使用 button 类型的组件 click 事件中如何获取formdata

### ISSUE THREAD

**Issue by shixiaoliu** [dream2023/vue-ele-form-generator#27]
formDesc: {
  btn: {
    label: '自定义',
    type: 'button',
    title: '按钮文字', // 按钮文字内容
    // 或者 title: '按钮文字'
    on: {
      // 按钮事件触发
      click () {
        console.log('clicked')
        **// 这边如何获取 formdata 的值**
      }
    }
  }
}

**Comment by shixiaoliu** [comment]
额。。。 想到了
data(){
   const _this = this
   return (
     btn:{
        on: {
                      click() {
                                console.log(_this.formData.phone)
                      }
               }
     }
   )
}

**Comment by dream2023** [comment]
你这方法有些过时了，箭头函数就行了
```js
click: () => {
	this. formData.phone
}
```

**Comment by shixiaoliu** [comment]
多谢
