### ISSUE TITLE
能提供将表单生成器嵌入自己项目的方法吗

### ISSUE THREAD

**Issue by mhlywxl** [dream2023/vue-ele-form-generator#28]

**Comment by dream2023** [comment]
目前有两种方式，一种是iframe嵌套和微前端接入，今天晚上会写一篇文章介绍这两种方式

**Comment by dream2023** [comment]
https://github.com/dream2023/vue-ele-form-generator/wiki/%E5%A6%82%E4%BD%95%E5%B0%86vue-form-generator%E9%9B%86%E6%88%90%E5%88%B0%E5%B7%B2%E6%9C%89%E9%A1%B9%E7%9B%AE

请看文章
