### ISSUE TITLE
该项目生成的表单不能用在vue2项目中是吗

### ISSUE THREAD

**Issue by ichdish** [dream2023/vue-ele-form-generator#31]
生成的表单如何在vue2项目中使用？

**Comment by dream2023** [comment]
目前不支持，具体请看


https://github.com/dream2023/vue-ele-form-generator/wiki/%E5%A6%82%E4%BD%95%E5%B0%86vue-form-generator%E9%9B%86%E6%88%90%E5%88%B0%E5%B7%B2%E6%9C%89%E9%A1%B9%E7%9B%AE
