### ISSUE TITLE
计划如何做各个组件的联动

### ISSUE THREAD

**Issue by liangwenle** [dream2023/vue-ele-form-generator#33]
场景一
有两个组件， 是否组件和input组件
如果选择是，则input 可以编辑，否则 反之；

场景二
有两个组件， 是否组件和单选组件
如果选择是，则单选组件的选项用A数据源，否这用B数据源

可以分享一下你的思路吗

**Comment by dream2023** [comment]
目前还没有好的可视化解决方案，但尽力避免写代码的方式

**Comment by liangwenle** [comment]
https://www.yuque.com/chaojie-vjiel/vbwzgu/loffm6  这里我找到了一些答案了。

**Comment by dream2023** [comment]
> https://www.yuque.com/chaojie-vjiel/vbwzgu/loffm6 这里我找到了一些答案了。

我说的是可视化操作

**Comment by liangwenle** [comment]
是的，可视化的确比较麻烦
