### ISSUE TITLE
希望能支持移动端排版

### ISSUE THREAD

**Issue by YiuTerran** [dream2023/vue-ele-form-generator#37]
现在项目一般只做pc端的需求比较少，很多时候都要跨端，需要做成自适应的网页。希望项目能支持移动端的预览调试。

感谢作者🙏

**Comment by YiuTerran** [comment]
另外就是阿里有个项目，alibaba/formily，感觉可以参考一下

**Comment by dream2023** [comment]
一般管理系统需要手机登录吗？我个人觉得应该不需要吧？

**Comment by YiuTerran** [comment]
你想窄了，实际上ToB项目很多要在手机上操作的。比如走流程审批，一般都是表单引擎配合工作流引擎，手机电脑上各搞一套。钉钉的表单就是专门给手机操作的，毕竟是移动办公时代了。

**Comment by dream2023** [comment]
> 你想窄了，实际上ToB项目很多要在手机上操作的。比如走流程审批，一般都是表单引擎配合工作流引擎，手机电脑上各搞一套。钉钉的表单就是专门给手机操作的，毕竟是移动办公时代了。

理解
