### ISSUE TITLE
没有组件数据

### ISSUE THREAD

**Issue by cute-angelia** [dream2023/vue-ele-form-generator#4]
![image](https://user-images.githubusercontent.com/26561606/62688213-fc750200-b9fa-11e9-8b76-90b6c8b8f9ee.png)

https://dream2023.github.io/form/

代码里面并没有组件数据

**Comment by dream2023** [comment]
![image](https://user-images.githubusercontent.com/19297757/62691594-93dd5380-ba01-11e9-9f53-0d1a68b0e028.png)

你指的组件数据是什么？

**Comment by cute-angelia** [comment]
我拖动了一个input 和 upload 组件, 这个代码里面没有2个组件的相关代码呢

**Comment by dream2023** [comment]
![image](https://user-images.githubusercontent.com/19297757/62691775-eb7bbf00-ba01-11e9-9572-72d554f5bfb5.png)
在这里呢

**Comment by cute-angelia** [comment]
这个工具不生成 ele-input  和 ele-upload 那些东西吗?

**Comment by dream2023** [comment]
不生成，用的我写的另外一个组件，数据驱动： https://github.com/dream2023/vue-ele-form，看看README.md,，口号是：1行html解决整个表单！

**Comment by cute-angelia** [comment]
尴尬, 原来如此.. sorry
